// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQ54lzody34yomprZ11jW-oOTEZ0kqSQ',
    appId: '1:872827026050:web:2ef743890ecaffa67c129b',
    messagingSenderId: '872827026050',
    projectId: 'friends-06162022',
    authDomain: 'friends-06162022.firebaseapp.com',
    storageBucket: 'friends-06162022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFqhAPmoLZqV_mYx7vMacDgYRtHyIA5Pc',
    appId: '1:872827026050:android:d534c65a2dd710397c129b',
    messagingSenderId: '872827026050',
    projectId: 'friends-06162022',
    storageBucket: 'friends-06162022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdzHlN2pxmQvLmbC8nmm6mkXxTh8Z1eic',
    appId: '1:872827026050:ios:68a536a204c678047c129b',
    messagingSenderId: '872827026050',
    projectId: 'friends-06162022',
    storageBucket: 'friends-06162022.appspot.com',
    iosClientId: '872827026050-qilqblms83fnqbqt0h01bv94vovv519m.apps.googleusercontent.com',
    iosBundleId: 'com.example.friends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdzHlN2pxmQvLmbC8nmm6mkXxTh8Z1eic',
    appId: '1:872827026050:ios:68a536a204c678047c129b',
    messagingSenderId: '872827026050',
    projectId: 'friends-06162022',
    storageBucket: 'friends-06162022.appspot.com',
    iosClientId: '872827026050-qilqblms83fnqbqt0h01bv94vovv519m.apps.googleusercontent.com',
    iosBundleId: 'com.example.friends',
  );
}
